name: Build Padavan

on: 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gawk pkg-config gettext automake autoconf libtool libtool-bin \
          autopoint libz-dev liblzo2-dev liblzma-dev libncurses5-dev libncursesw5-dev libsqlite3-dev \
          libssl-dev git python3-setuptools python3-mako help2man nano mc

      - name: Prepare Toolchain
        run: |
          cd toolchain-mipsel
          ./clean_sources
          ./build_toolchain

      - name: Build Firmware
        run: |
          cd trunk
          cp ../tl_wr841n-v14.config .config 
          ./clear_tree
          ./build_firmware

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Padavan_WR841N_V14
          path: trunk/images/*.trx
