name: Build Padavan-NG WR841N-V14

on:
  workflow_dispatch: # Запуск кнопкой из вкладки Actions

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gawk pkg-config gettext automake autoconf libtool libtool-bin \
          autopoint libz-dev liblzo2-dev liblzma-dev libncurses5-dev libncursesw5-dev libsqlite3-dev \
          libssl-dev git python3-setuptools python3-mako help2man nano

      - name: Build Toolchain
        run: |
          # В padavan-ng папка называется именно toolchain
          cd toolchain
          ./clean_sources
          ./build_toolchain

      - name: Build Firmware
        run: |
          cd trunk
          # Твой файл должен называться build.config и лежать в корне репо
          # Если он называется иначе, поправь имя ниже
          cp ../build.config .config
          
          # Очистка и запуск сборки
          ./clear_tree
          ./build_firmware

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: Padavan_NG_WR841N_V14
          path: trunk/images/*.trx
